#!/usr/bin/env bash
# transfer a file from a clinet to server using scp

path="$1"
ip="$2"
username="$3"
sshkey_path="$4"

scp -o StrictHostKeyChecking=no -i "$sshkey_path" "$path" "${username}@${ip}":"$path"

