#!/bin/bash
# trnasfer file from clinet to server

usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -lt 4 ]; then
	usage
	exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "${username}@${server_ip}":"$file_path"
