#!/usr/bin/env bash
# configure Nginx redirection

sed -i 's@location / {.*@&\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }@' /etc/nginx/sites-available/default

sudo service nginx restart

curl -sI localhost/redirect_me/

